name: gravicom - Graphical Visualization of Communities
pygments: true
markdown: rdiscount
baseurl: /gravicom
permalink: :categories/:title
rdiscount extensions: [smart]

links:
- name: docs
  href: '#'
  class: fa-sitemap
  target: _self
- name: app
  href: http://glimmer.rstudio.com/andeek/gravicom
  class: fa-external-link
  target: _blank
- name: github
  href: http://github.com/andeek/gravicom
  class: fa-github
  target: _blank



