name: gravicom
pygments: true
markdown: rdiscount
baseurl: /gravicom
permalink: :categories/:title
rdiscount extensions: [smart]

links:
- name: gravicom
  href: http://andeek.shinyapps.io/gravicom
  class: fa-home
  target: _blank
  level: 1
- name: help
  href: ''
  class: fa-question-circle
  target: _self
  level: 1
- name: contact
  href: 'http://andeekaplan.com'
  class: fa-envelope
  target: _blank
  level: 1
- name: github
  href: http://github.com/andeek/gravicom
  class: fa-github
  target: _blank
  level: 1

